<?php
/**
 * pc_qr_src() -- the one place a QR code URL is built.
 *
 * Extracted from app-cards.php because two components now need it: that file
 * (the /download-our-app cards) and the compact app row in
 * components/shared/app-download-banner.php, which closes most pages.
 * Requiring the whole of app-cards.php just to reach the function would drag
 * in its $appCards data and its markup, so the helper lives on its own.
 *
 * Guarded because both callers may be on the same page: /download-our-app
 * renders the cards AND ends with the app row.
 *
 * The codes are generated by a third party at render time. That is fine for a
 * QR -- it encodes a public store URL, there is nothing private in it, and if
 * the service is unreachable the <img> simply fails while the store badges
 * beside it keep working. Do not move anything user-specific into one.
 */
if (!function_exists('pc_qr_src')) {
  function pc_qr_src(string $target): string
  {
    return 'https://api.qrserver.com/v1/create-qr-code/?size=220x220&margin=10&ecc=H&data=' . rawurlencode($target);
  }
}
